spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver
    username: authserver
    password: authserver
    hikari:
      data-source-properties:
        useSSL: false
  jpa:
    hibernate:
      ddl-auto: update   