# see: https://aws.amazon.com/blogs/compute/using-container-image-support-for-aws-lambda-with-aws-sam/

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for csvtransform

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# timeout and memory config for the lambda function
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  ParseCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: csv-transform
      PackageType: Image
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET_NAME: anyuse
          IN_PREFIX: in
          OUT_PREFIX: out
      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/all_policy_templates.yaml
      Policies:
        - S3ReadPolicy:
            BucketName: anyuse
        - S3WritePolicy:
            BucketName: anyuse
    Metadata:
      DockerTag: v1
      DockerContext: ./
      Dockerfile: Dockerfile      